add_two_numbers/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('firstapp.urls'))
]

firstapp/urls.py
from django.urls import path
from firstapp import views

app_name="basicapp"
urlpatterns = [

path('',views.index,name="index"),
path('add/',views.add,name="add")

]

firstapp/models.py
from django.db import models

# Create your models here.

firstapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,"index.html")

def add(request):
    val=request.POST.get('a')
    val2=request.POST.get('b')
    s=int(val)+int(val2)

    return render(request,"add.html",context={'sum':s})

firstapp/templates/add.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>NOw wait 4 the result</h2>
    {{sum}}
  </body>
</html>

firstapp/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Add two numbers in Django</h1>
    <form class="" action={%url 'basicapp:add'%} method="POST">
      <label for="a">Enter First Number:</label>
      &nbsp &nbsp
      <input id="a" type="text" name="a" value=""><br><br>
      <label for="b">Enter Second Number:</label>
      <input id="b" type="text" name="b" value=""><br><br>
      {% csrf_token %}
      <input type="submit" name="" value="submit">
    </form>

  </body>
</html>